#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace CelloStore.Data	
{
	public partial class AutoNumber
	{
		private string formCode;
		public virtual string FormCode
		{
			get
			{
				return this.formCode;
			}
			set
			{
				this.formCode = value;
			}
		}
		
		private int year;
		public virtual int Year
		{
			get
			{
				return this.year;
			}
			set
			{
				this.year = value;
			}
		}
		
		private int lastNumber;
		public virtual int LastNumber
		{
			get
			{
				return this.lastNumber;
			}
			set
			{
				this.lastNumber = value;
			}
		}
		
	}
}
#pragma warning restore 1591
