#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CelloStore.Data;

namespace CelloStore.Data	
{
	public partial class Invoice
	{
		private int id;
		public virtual int Id
		{
			get
			{
				return this.id;
			}
			set
			{
				this.id = value;
			}
		}
		
		private string invoiceNo;
		public virtual string InvoiceNo
		{
			get
			{
				return this.invoiceNo;
			}
			set
			{
				this.invoiceNo = value;
			}
		}
		
		private string deliveryNo;
		public virtual string DeliveryNo
		{
			get
			{
				return this.deliveryNo;
			}
			set
			{
				this.deliveryNo = value;
			}
		}
		
		private int orderId;
		public virtual int OrderId
		{
			get
			{
				return this.orderId;
			}
			set
			{
				this.orderId = value;
			}
		}
		
		private int orderDetailId;
		public virtual int OrderDetailId
		{
			get
			{
				return this.orderDetailId;
			}
			set
			{
				this.orderDetailId = value;
			}
		}
		
		private DateTime date;
		public virtual DateTime Date
		{
			get
			{
				return this.date;
			}
			set
			{
				this.date = value;
			}
		}
		
		private string invoiceToName;
		public virtual string InvoiceToName
		{
			get
			{
				return this.invoiceToName;
			}
			set
			{
				this.invoiceToName = value;
			}
		}
		
		private string invoiceToAddress;
		public virtual string InvoiceToAddress
		{
			get
			{
				return this.invoiceToAddress;
			}
			set
			{
				this.invoiceToAddress = value;
			}
		}
		
		private string invoiceToEmail;
		public virtual string InvoiceToEmail
		{
			get
			{
				return this.invoiceToEmail;
			}
			set
			{
				this.invoiceToEmail = value;
			}
		}
		
		private decimal amount;
		public virtual decimal Amount
		{
			get
			{
				return this.amount;
			}
			set
			{
				this.amount = value;
			}
		}
		
		private int status;
		public virtual int Status
		{
			get
			{
				return this.status;
			}
			set
			{
				this.status = value;
			}
		}
		
		private string lastChangedStatusBy;
		public virtual string LastChangedStatusBy
		{
			get
			{
				return this.lastChangedStatusBy;
			}
			set
			{
				this.lastChangedStatusBy = value;
			}
		}
		
		private DateTime? lastChangedStatusWhen;
		public virtual DateTime? LastChangedStatusWhen
		{
			get
			{
				return this.lastChangedStatusWhen;
			}
			set
			{
				this.lastChangedStatusWhen = value;
			}
		}
		
		private string notes;
		public virtual string Notes
		{
			get
			{
				return this.notes;
			}
			set
			{
				this.notes = value;
			}
		}
		
		private DateTime createdWhen;
		public virtual DateTime CreatedWhen
		{
			get
			{
				return this.createdWhen;
			}
			set
			{
				this.createdWhen = value;
			}
		}
		
		private string createdBy;
		public virtual string CreatedBy
		{
			get
			{
				return this.createdBy;
			}
			set
			{
				this.createdBy = value;
			}
		}
		
		private DateTime changedWhen;
		public virtual DateTime ChangedWhen
		{
			get
			{
				return this.changedWhen;
			}
			set
			{
				this.changedWhen = value;
			}
		}
		
		private string changedBy;
		public virtual string ChangedBy
		{
			get
			{
				return this.changedBy;
			}
			set
			{
				this.changedBy = value;
			}
		}
		
		private OrderDetail orderDetail;
		public virtual OrderDetail OrderDetail
		{
			get
			{
				return this.orderDetail;
			}
			set
			{
				this.orderDetail = value;
			}
		}
		
		private Order order;
		public virtual Order Order
		{
			get
			{
				return this.order;
			}
			set
			{
				this.order = value;
			}
		}
		
	}
}
#pragma warning restore 1591
