#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CelloStore.Data;

namespace CelloStore.Data	
{
	public partial class Order
	{
		private int id;
		public virtual int Id
		{
			get
			{
				return this.id;
			}
			set
			{
				this.id = value;
			}
		}
		
		private string orderNo;
		public virtual string OrderNo
		{
			get
			{
				return this.orderNo;
			}
			set
			{
				this.orderNo = value;
			}
		}
		
		private DateTime orderDate;
		public virtual DateTime OrderDate
		{
			get
			{
				return this.orderDate;
			}
			set
			{
				this.orderDate = value;
			}
		}
		
		private int personId;
		public virtual int PersonId
		{
			get
			{
				return this.personId;
			}
			set
			{
				this.personId = value;
			}
		}
		
		private bool secretSenderName;
		public virtual bool SecretSenderName
		{
			get
			{
				return this.secretSenderName;
			}
			set
			{
				this.secretSenderName = value;
			}
		}
		
		private bool callRecipientFirst;
		public virtual bool CallRecipientFirst
		{
			get
			{
				return this.callRecipientFirst;
			}
			set
			{
				this.callRecipientFirst = value;
			}
		}
		
		private string recipientName;
		public virtual string RecipientName
		{
			get
			{
				return this.recipientName;
			}
			set
			{
				this.recipientName = value;
			}
		}
		
		private string recipientEmail;
		public virtual string RecipientEmail
		{
			get
			{
				return this.recipientEmail;
			}
			set
			{
				this.recipientEmail = value;
			}
		}
		
		private string recipientCompanyName;
		public virtual string RecipientCompanyName
		{
			get
			{
				return this.recipientCompanyName;
			}
			set
			{
				this.recipientCompanyName = value;
			}
		}
		
		private int recipientLocationTypeId;
		public virtual int RecipientLocationTypeId
		{
			get
			{
				return this.recipientLocationTypeId;
			}
			set
			{
				this.recipientLocationTypeId = value;
			}
		}
		
		private string recipientAddress;
		public virtual string RecipientAddress
		{
			get
			{
				return this.recipientAddress;
			}
			set
			{
				this.recipientAddress = value;
			}
		}
		
		private string recipientPhoneNumber;
		public virtual string RecipientPhoneNumber
		{
			get
			{
				return this.recipientPhoneNumber;
			}
			set
			{
				this.recipientPhoneNumber = value;
			}
		}
		
		private DateTime? deliveryDate;
		public virtual DateTime? DeliveryDate
		{
			get
			{
				return this.deliveryDate;
			}
			set
			{
				this.deliveryDate = value;
			}
		}
		
		private byte deliveryTime;
		public virtual byte DeliveryTime
		{
			get
			{
				return this.deliveryTime;
			}
			set
			{
				this.deliveryTime = value;
			}
		}
		
		private string voucherCode;
		public virtual string VoucherCode
		{
			get
			{
				return this.voucherCode;
			}
			set
			{
				this.voucherCode = value;
			}
		}
		
		private string toCardMessage;
		public virtual string ToCardMessage
		{
			get
			{
				return this.toCardMessage;
			}
			set
			{
				this.toCardMessage = value;
			}
		}
		
		private string fromCardMessage;
		public virtual string FromCardMessage
		{
			get
			{
				return this.fromCardMessage;
			}
			set
			{
				this.fromCardMessage = value;
			}
		}
		
		private string cardMessage;
		public virtual string CardMessage
		{
			get
			{
				return this.cardMessage;
			}
			set
			{
				this.cardMessage = value;
			}
		}
		
		private int? paymentMethodId;
		public virtual int? PaymentMethodId
		{
			get
			{
				return this.paymentMethodId;
			}
			set
			{
				this.paymentMethodId = value;
			}
		}
		
		private string notes;
		public virtual string Notes
		{
			get
			{
				return this.notes;
			}
			set
			{
				this.notes = value;
			}
		}
		
		private byte uniquePayment;
		public virtual byte UniquePayment
		{
			get
			{
				return this.uniquePayment;
			}
			set
			{
				this.uniquePayment = value;
			}
		}
		
		private int orderStatusId;
		public virtual int OrderStatusId
		{
			get
			{
				return this.orderStatusId;
			}
			set
			{
				this.orderStatusId = value;
			}
		}
		
		private DateTime createdWhen;
		public virtual DateTime CreatedWhen
		{
			get
			{
				return this.createdWhen;
			}
			set
			{
				this.createdWhen = value;
			}
		}
		
		private string createdBy;
		public virtual string CreatedBy
		{
			get
			{
				return this.createdBy;
			}
			set
			{
				this.createdBy = value;
			}
		}
		
		private DateTime changedWhen;
		public virtual DateTime ChangedWhen
		{
			get
			{
				return this.changedWhen;
			}
			set
			{
				this.changedWhen = value;
			}
		}
		
		private string changedBy;
		public virtual string ChangedBy
		{
			get
			{
				return this.changedBy;
			}
			set
			{
				this.changedBy = value;
			}
		}
		
		private int orderAreaId;
		public virtual int OrderAreaId
		{
			get
			{
				return this.orderAreaId;
			}
			set
			{
				this.orderAreaId = value;
			}
		}
		
		private string recipientState;
		public virtual string RecipientState
		{
			get
			{
				return this.recipientState;
			}
			set
			{
				this.recipientState = value;
			}
		}
		
		private string recipientCity;
		public virtual string RecipientCity
		{
			get
			{
				return this.recipientCity;
			}
			set
			{
				this.recipientCity = value;
			}
		}
		
		private Person person;
		public virtual Person Person
		{
			get
			{
				return this.person;
			}
			set
			{
				this.person = value;
			}
		}
		
		private PaymentMethod paymentMethod;
		public virtual PaymentMethod PaymentMethod
		{
			get
			{
				return this.paymentMethod;
			}
			set
			{
				this.paymentMethod = value;
			}
		}
		
		private AddressType addressType;
		public virtual AddressType AddressType
		{
			get
			{
				return this.addressType;
			}
			set
			{
				this.addressType = value;
			}
		}
		
		private Area area;
		public virtual Area Area
		{
			get
			{
				return this.area;
			}
			set
			{
				this.area = value;
			}
		}
		
		private IList<OrderStatusHistory> orderStatusHistories = new List<OrderStatusHistory>();
		public virtual IList<OrderStatusHistory> OrderStatusHistories
		{
			get
			{
				return this.orderStatusHistories;
			}
		}
		
		private IList<OrderDetail> orderDetails = new List<OrderDetail>();
		public virtual IList<OrderDetail> OrderDetails
		{
			get
			{
				return this.orderDetails;
			}
		}
		
		private IList<PaymentConfirmation> paymentConfirmations = new List<PaymentConfirmation>();
		public virtual IList<PaymentConfirmation> PaymentConfirmations
		{
			get
			{
				return this.paymentConfirmations;
			}
		}
		
	}
}
#pragma warning restore 1591
