#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CelloStore.Data;

namespace CelloStore.Data	
{
	public partial class OrderStatusHistory
	{
		private int id;
		public virtual int Id
		{
			get
			{
				return this.id;
			}
			set
			{
				this.id = value;
			}
		}
		
		private int orderId;
		public virtual int OrderId
		{
			get
			{
				return this.orderId;
			}
			set
			{
				this.orderId = value;
			}
		}
		
		private DateTime effectiveDate;
		public virtual DateTime EffectiveDate
		{
			get
			{
				return this.effectiveDate;
			}
			set
			{
				this.effectiveDate = value;
			}
		}
		
		private int orderStatusId;
		public virtual int OrderStatusId
		{
			get
			{
				return this.orderStatusId;
			}
			set
			{
				this.orderStatusId = value;
			}
		}
		
		private string notes;
		public virtual string Notes
		{
			get
			{
				return this.notes;
			}
			set
			{
				this.notes = value;
			}
		}
		
		private bool isActive;
		public virtual bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{
				this.isActive = value;
			}
		}
		
		private string createdBy;
		public virtual string CreatedBy
		{
			get
			{
				return this.createdBy;
			}
			set
			{
				this.createdBy = value;
			}
		}
		
		private DateTime createdDate;
		public virtual DateTime CreatedDate
		{
			get
			{
				return this.createdDate;
			}
			set
			{
				this.createdDate = value;
			}
		}
		
		private bool sendMail;
		public virtual bool SendMail
		{
			get
			{
				return this.sendMail;
			}
			set
			{
				this.sendMail = value;
			}
		}
		
		private Order order;
		public virtual Order Order
		{
			get
			{
				return this.order;
			}
			set
			{
				this.order = value;
			}
		}
		
	}
}
#pragma warning restore 1591
