#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace CelloStore.Data	
{
	public partial class OrderStatus
	{
		private int id;
		public virtual int Id
		{
			get
			{
				return this.id;
			}
			set
			{
				this.id = value;
			}
		}
		
		private string name;
		public virtual string Name
		{
			get
			{
				return this.name;
			}
			set
			{
				this.name = value;
			}
		}
		
		private string emailTemplate;
		public virtual string EmailTemplate
		{
			get
			{
				return this.emailTemplate;
			}
			set
			{
				this.emailTemplate = value;
			}
		}
		
		private DateTime changedWhen;
		public virtual DateTime ChangedWhen
		{
			get
			{
				return this.changedWhen;
			}
			set
			{
				this.changedWhen = value;
			}
		}
		
		private string changedBy;
		public virtual string ChangedBy
		{
			get
			{
				return this.changedBy;
			}
			set
			{
				this.changedBy = value;
			}
		}
		
		private bool? sendMail;
		public virtual bool? SendMail
		{
			get
			{
				return this.sendMail;
			}
			set
			{
				this.sendMail = value;
			}
		}
		
	}
}
#pragma warning restore 1591
