#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CelloStore.Data;

namespace CelloStore.Data	
{
	public partial class PaymentConfirmation
	{
		private int id;
		public virtual int Id
		{
			get
			{
				return this.id;
			}
			set
			{
				this.id = value;
			}
		}
		
		private int orderId;
		public virtual int OrderId
		{
			get
			{
				return this.orderId;
			}
			set
			{
				this.orderId = value;
			}
		}
		
		private int paymentMethodId;
		public virtual int PaymentMethodId
		{
			get
			{
				return this.paymentMethodId;
			}
			set
			{
				this.paymentMethodId = value;
			}
		}
		
		private int? bankId;
		public virtual int? BankId
		{
			get
			{
				return this.bankId;
			}
			set
			{
				this.bankId = value;
			}
		}
		
		private decimal amount;
		public virtual decimal Amount
		{
			get
			{
				return this.amount;
			}
			set
			{
				this.amount = value;
			}
		}
		
		private string notes;
		public virtual string Notes
		{
			get
			{
				return this.notes;
			}
			set
			{
				this.notes = value;
			}
		}
		
		private DateTime? verifiedWhen;
		public virtual DateTime? VerifiedWhen
		{
			get
			{
				return this.verifiedWhen;
			}
			set
			{
				this.verifiedWhen = value;
			}
		}
		
		private int? verifiedByPersonId;
		public virtual int? VerifiedByPersonId
		{
			get
			{
				return this.verifiedByPersonId;
			}
			set
			{
				this.verifiedByPersonId = value;
			}
		}
		
		private DateTime createdWhen;
		public virtual DateTime CreatedWhen
		{
			get
			{
				return this.createdWhen;
			}
			set
			{
				this.createdWhen = value;
			}
		}
		
		private string createdBy;
		public virtual string CreatedBy
		{
			get
			{
				return this.createdBy;
			}
			set
			{
				this.createdBy = value;
			}
		}
		
		private DateTime changedWhen;
		public virtual DateTime ChangedWhen
		{
			get
			{
				return this.changedWhen;
			}
			set
			{
				this.changedWhen = value;
			}
		}
		
		private string changedBy;
		public virtual string ChangedBy
		{
			get
			{
				return this.changedBy;
			}
			set
			{
				this.changedBy = value;
			}
		}
		
		private DateTime date;
		public virtual DateTime Date
		{
			get
			{
				return this.date;
			}
			set
			{
				this.date = value;
			}
		}
		
		private PaymentMethod paymentMethod;
		public virtual PaymentMethod PaymentMethod
		{
			get
			{
				return this.paymentMethod;
			}
			set
			{
				this.paymentMethod = value;
			}
		}
		
		private Order order;
		public virtual Order Order
		{
			get
			{
				return this.order;
			}
			set
			{
				this.order = value;
			}
		}
		
		private Bank bank;
		public virtual Bank Bank
		{
			get
			{
				return this.bank;
			}
			set
			{
				this.bank = value;
			}
		}
		
	}
}
#pragma warning restore 1591
