#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using CelloStore.Data;

namespace CelloStore.Data	
{
	public partial class Product
	{
		private int id;
		public virtual int Id
		{
			get
			{
				return this.id;
			}
			set
			{
				this.id = value;
			}
		}
		
		private string code;
		public virtual string Code
		{
			get
			{
				return this.code;
			}
			set
			{
				this.code = value;
			}
		}
		
		private string name;
		public virtual string Name
		{
			get
			{
				return this.name;
			}
			set
			{
				this.name = value;
			}
		}
		
		private decimal unitPrice;
		public virtual decimal UnitPrice
		{
			get
			{
				return this.unitPrice;
			}
			set
			{
				this.unitPrice = value;
			}
		}
		
		private bool isActive;
		public virtual bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{
				this.isActive = value;
			}
		}
		
		private string photo;
		public virtual string Photo
		{
			get
			{
				return this.photo;
			}
			set
			{
				this.photo = value;
			}
		}
		
		private DateTime createdWhen;
		public virtual DateTime CreatedWhen
		{
			get
			{
				return this.createdWhen;
			}
			set
			{
				this.createdWhen = value;
			}
		}
		
		private string createdBy;
		public virtual string CreatedBy
		{
			get
			{
				return this.createdBy;
			}
			set
			{
				this.createdBy = value;
			}
		}
		
		private DateTime changedWhen;
		public virtual DateTime ChangedWhen
		{
			get
			{
				return this.changedWhen;
			}
			set
			{
				this.changedWhen = value;
			}
		}
		
		private string changedBy;
		public virtual string ChangedBy
		{
			get
			{
				return this.changedBy;
			}
			set
			{
				this.changedBy = value;
			}
		}
		
		private string description;
		public virtual string Description
		{
			get
			{
				return this.description;
			}
			set
			{
				this.description = value;
			}
		}
		
		private bool isFeatured;
		public virtual bool IsFeatured
		{
			get
			{
				return this.isFeatured;
			}
			set
			{
				this.isFeatured = value;
			}
		}
		
		private IList<Area> areas = new List<Area>();
		public virtual IList<Area> Areas
		{
			get
			{
				return this.areas;
			}
		}
		
		private IList<Category> categories = new List<Category>();
		public virtual IList<Category> Categories
		{
			get
			{
				return this.categories;
			}
		}
		
		private IList<OrderDetail> orderDetails = new List<OrderDetail>();
		public virtual IList<OrderDetail> OrderDetails
		{
			get
			{
				return this.orderDetails;
			}
		}
		
		private IList<Tag> tags = new List<Tag>();
		public virtual IList<Tag> Tags
		{
			get
			{
				return this.tags;
			}
		}
		
	}
}
#pragma warning restore 1591
