#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace CelloStore.Data	
{
	public partial class Showcase
	{
		private int id;
		public virtual int Id
		{
			get
			{
				return this.id;
			}
			set
			{
				this.id = value;
			}
		}
		
		private string title;
		public virtual string Title
		{
			get
			{
				return this.title;
			}
			set
			{
				this.title = value;
			}
		}
		
		private string description;
		public virtual string Description
		{
			get
			{
				return this.description;
			}
			set
			{
				this.description = value;
			}
		}
		
		private string imagePath;
		public virtual string ImagePath
		{
			get
			{
				return this.imagePath;
			}
			set
			{
				this.imagePath = value;
			}
		}
		
		private string priceImagePath;
		public virtual string PriceImagePath
		{
			get
			{
				return this.priceImagePath;
			}
			set
			{
				this.priceImagePath = value;
			}
		}
		
		private DateTime? fromDate;
		public virtual DateTime? FromDate
		{
			get
			{
				return this.fromDate;
			}
			set
			{
				this.fromDate = value;
			}
		}
		
		private DateTime? toDate;
		public virtual DateTime? ToDate
		{
			get
			{
				return this.toDate;
			}
			set
			{
				this.toDate = value;
			}
		}
		
		private bool first;
		public virtual bool First
		{
			get
			{
				return this.first;
			}
			set
			{
				this.first = value;
			}
		}
		
		private bool isActive;
		public virtual bool IsActive
		{
			get
			{
				return this.isActive;
			}
			set
			{
				this.isActive = value;
			}
		}
		
		private string url;
		public virtual string Url
		{
			get
			{
				return this.url;
			}
			set
			{
				this.url = value;
			}
		}
		
		private DateTime createdWhen;
		public virtual DateTime CreatedWhen
		{
			get
			{
				return this.createdWhen;
			}
			set
			{
				this.createdWhen = value;
			}
		}
		
		private string createdBy;
		public virtual string CreatedBy
		{
			get
			{
				return this.createdBy;
			}
			set
			{
				this.createdBy = value;
			}
		}
		
		private DateTime changedWhen;
		public virtual DateTime ChangedWhen
		{
			get
			{
				return this.changedWhen;
			}
			set
			{
				this.changedWhen = value;
			}
		}
		
		private string changedBy;
		public virtual string ChangedBy
		{
			get
			{
				return this.changedBy;
			}
			set
			{
				this.changedBy = value;
			}
		}
		
		private int? extLinkType;
		public virtual int? ExtLinkType
		{
			get
			{
				return this.extLinkType;
			}
			set
			{
				this.extLinkType = value;
			}
		}
		
		private int? articleId;
		public virtual int? ArticleId
		{
			get
			{
				return this.articleId;
			}
			set
			{
				this.articleId = value;
			}
		}
		
	}
}
#pragma warning restore 1591
